export const QUOTES = [
  "Bring flowers or a small gift to someone going through a tough time",
  "Write a thank-you note to someone who has impacted your life.",
  "Cook a meal for a neighbour or friend in need.",
  "Smile and greet strangers during your daily routine.",
  "Take a 10-minute walk during breaks to refresh your mind.",
  "Replace one coffee with green tea for a calming boost.",
  "Hold the door open for someone entering behind you.",
  "Respect personal boundaries and time outside work hours.",
  "Offer a genuine compliment on someone’s effort or achievement.",
  "Pay for a stranger’s coffee or meal.",
  "Support a local artist or small business.",
  "Plant a tree in honour of someone you admire.",
  "Donate books to a school or library.",
  "Write a positive review for a business or service you appreciate.",
  "Offer your seat to someone who needs it more.",
  "Stand up for someone being treated unfairly.",
  "Visit a nursing home and spend time with residents.",
  "Leave positive notes in public places for strangers to find.",
  "Leave a thank-you note for your office cleaning staff or support team.",
  "Buy coffee or lunch for a colleague unexpectedly.",
];
