import { Urbanist, Allura, Roboto, Inter } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });
const allura = Allura({ subsets: ["latin"], weight: "400", variable: "--font-allura" });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"], variable: "--font-roboto" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} ${allura.variable} ${roboto.variable} ${inter.variable}`}>{children}</body>
    </html>
  );
}
